name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying Universal FrameWork
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build universal FrameWork
        run: ./.github/secrets/build_universal_fmk.sh