name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme "Flagship" -destination "name=iPhone 8,OS=13.6"
    - name: Update Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) -J 'flagship-ios'
