name: Swift

on:
  push:
    branches: [ release2.0.0 ]
  pull_request:
    branches: [ release2.0.0 ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme "Flagship" -destination "name=iPhone 8,OS=13.6"
    - name: Update Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash)

