name: swiftlint
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Xcode 12.4
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Lint
        run: swiftlint 
