name: Swift

on:
  push:
    branches: [ testci ]
  pull_request:
    branches: [ testci ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme "Flagship" -destination "name=iPhone 8,OS=13.6"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

